const rawGuests = `
ARAYA EMILIO Y JOSEFA|1
AWAD PABLO Y JAVIERA RIEDEL|2
BACARREZA MARIANA Y JAVIER MELERO|12
BAGHETTI ANDREA E IGNACIO ROSAS|12
BAGHETTI MARIA PAZ|2
BAGHETTI PIERO Y PAULINA ORELLANA|24
BALMACEDA GASPAR Y PAREJA|8
BALMACEDA MATIAS Y BERNARDITA SWIBURN|21
BARROS ALEJANDRO Y PAREJA|9
BAUZÁ GLORIA Y RAFAEL CISTERNAS|4
BEPROCAL EDUARDO Y ROSA REYES|39
BIER DOMINGA|26
BIER SANTIAGO|26
BOETCH BENJAMIN Y SEÑORA|5
BONGARDT ERICK Y CARMEN HOLMGREN|16
BONGARDT MATIAS Y ROCIO LABANDUR|38
BULNES ARTURO Y SEÑORA|45
BULNES FELIPE Y SEÑORA|19
BULNES FERNANDO Y SEÑORA|17
BULNES JOSE MIGUEL Y SEÑORA|20
BULNES JUAN CARLOS Y SEÑORA|46
BULNES MANUEL Y SEÑORA|45
BULNES MARIA TERESA Y MARIDO|19
BULNES NICOLAS Y PAREJA|9
BULNES SANTIAGO Y SEÑORA|19
CALVO MARIA JOSE Y MARIDO|20
CAMBIASO PIA|24
CAMPOS ALBERTO Y SEÑORA|5
CANESSA MARIO Y PATRICIA LUEJE|41
CASTRO EDUARDO Y MARÍA PAZ AMENABAR|41
CHAIGNEAU PILAR|24
CHARLIN ADOLFO Y NIEVES BENAVIDES|24
CISTERNAS JOSEFINA Y FRANCISCO SUTIL|4
CONCHA ALFREDO Y SEÑORA|18
CONCHA B. FERNANDO Y SEÑORA|6
CONCHA B. JUAN|8
CONCHA B. MIGUEL|8
CONCHA BERNARDITA Y MARIDO|19
CONCHA BERNARDO Y PAREJA|9
CONCHA CARLOS Y SEÑORA|20
CONCHA CARMEN Y MARIDO|46
CONCHA CATALINA Y MARIDO|18
CONCHA JOSE IGNACIO|41
CONCHA JOSE Y SEÑORA|31
CONCHA L. JUAN ENRIQUE Y SEÑORA|19
CONCHA MARGARITA Y MARIDO|46
CONCHA MERCEDES|31
CONCHA PILAR Y MARIDO|20
CONCHA SARA Y MARIDO|31
CONCHA SOFIA Y MARIDO|18
CONCHA U. FERNANDO Y SEÑORA|31
CONCHA U. JUAN ENRIQUE Y SEÑORA|31
CONCHA V. ALFREDO|26
CONCHA V. AUGUSTO|26
CONCHA V. JUANITA|26
CONCHA VICTORIA Y MARIDO|18
CONDELL CRISTIAN Y SEÑORA|17
CONDELL DIEGO|47
CONDELL JOSE ANTONIO Y SEÑORA|23
CONDELL PEDRO|26
CORBELLA ANTONIO Y SEÑORA|33
CORBELLA FRANCISCO Y SEÑORA|33
CORREA ALICIA Y MARIDO|35
CORREA ANDREA|37
CORREA CAROLA Y MARIDO|17
CORREA HERNAN Y SEÑORA|23
CORREA JACINTA Y ALEJANDRO LLOMPART|3
CORREA JOSE MIGUEL Y PATRICIA CONCHA|41
COUDEU MARTIN Y PAREJA|33
COUDEU PABLO Y SEÑORA|30
COUDEU MARIA JOSE Y PAREJA|5
CRUZ PATRICIO Y PAOLA CIBIE|15
CUADRA MARI|39
DE TORO VICENTE Y PAREJA|10
DIEZ JESUS Y SEÑORA|32
DOMEYKO JUAN Y PAREJA|8
DONAGGIO VINKA|29
ECHAVARRI TOMÁS Y SEÑORA|28
ECHAVARRI TOMAS|25
EFFA ALEJANDRA Y PAREJA|43
EFFA RICARDO Y SEÑORA|42
EGUIGUREN TOMAS Y PAREJA|11
ELLIS MANUEL Y CARLA GARBARINI|27
ESPAÑA LISA|4
ESTEBANEZ FERNANDO Y SEÑORA|28
FANTUZZI FLORENCIA Y CRISTIÁN ORTUZAR|12
FELIPE PLUBINS Y ROSARIO|1
FELIU ENRIQUE Y SEÑORA|35
FERNANDEZ MARCO Y ARLINE DE LAIRE|27
FERNANDEZ SEBASTIAN Y SEÑORA|17
FERNANDEZ SOFÍA Y DIEGO CHARLIN|13
FERNÁNDEZ SOFÍA Y NICOLÁS LOWENER|3
FERNÁNDEZ VALENTINA Y JUAN PABLO ZAÑARTU|13
FERNÁNDEZ DIEGO Y VERÓNICA GARBARINI|25
FERNÁNDEZ MARCO Y CLAUDIA JORQUERA|25
FERRAGUT HERNAN Y SEÑORA|44
FERRER JOSE Y SEÑORA|22
FLEISHMAN PEDRO Y ANDREA GARCÍA|14
FRANGIOLA CRISTIAN Y SEÑORA|30
FRIAS JUAN CARLOS Y SEÑORA|34
FUENTES IGNACIA Y PABLO GELLONA|13
FUENTES SEBASTIAN Y MACARENA NOGUERA|15
FUENZALIDA JORGE Y SEÑORA|7
FUENZALIDA JULIO Y PAREJA|9
FUENZALIDA RAMON Y SEÑORA|23
GABLER PABLO Y SEÑORA|44
GARCÍA ANTONIO Y MARÍA JOSÉ ALBARRÁN|21
GARCÍA FRANCISCA Y JUAN PABLO FIERRO|4
GARCÍA ANTONIO E IGNACIA GRIFFIN|14
GARCÍA DIEGO|14
GARCÍA ELISA|14
GARCÍA VICENTE Y FRANCISCA SILVA|14
GELLONA JUAN CARLOS|7
GINER FERNANDO Y CAROLINA CAMPOS|21
GODOY JAVIER Y PAREJA|44
GOYCOLEA NICOLAS|8
GROSS PATRICIO Y SEÑORA|35
GUZMAN RAIMUNDO Y SEÑORA|10
HARTWIG MAGDALENA Y ACOMPAÑANTE|12
HEVIA SERGIO Y PAREJA|10
HIDALGO JOAQUIN Y ISABEL JULLIAN|41
HOLHBERG ELISA Y JOSE FRANCISCO MELERO|3
HOLMGREN BEATRIZ|16
HOLMGREN CARLOS Y SARA UNDURRAGA|NOVIOS
HOLMGREN SEBASTIÁN Y ACOMPAÑANTE|NOVIOS
HOLMGREN CHARLIE Y SEÑORA|NOVIOS
HURTADO ERNESTO Y KARIN DEVIDTS|37
IIDES ARMANDO Y SEÑORA|28
ILLANES JOSE PEDRO Y PAULA ORELLANA|37
IZQUIERDO C. JOSE MANUEL Y PAREJA|11
JIMÉNEZ TERESITA Y CRISTÁN LONGUEIRA|2
JIMÉNEZ FRANCISCO Y TERESA GARCÉS|24
KARLEZI SERGIO Y SEÑORA|22
KOHAN RODRIGO Y MARÍA PAZ MELLADO|21
KOHAN SOFIA Y ACOMPAÑANTE|14
LABRA TRINIDAD Y PAREJA|20
LAMA SOFIA E ISMAEL ROBLES|13
LARRAIN ALICIA|29
LARRAIN ANA MARIA|29
LARRAIN FRANCISCO Y PAREJA|11
LARRAIN JOSE Y PAREJA|33
LARRAIN LEON Y SEÑORA|45
LARRAIN PAULA Y PAREJA|23
LARRAIN SAMUEL Y SEÑORA|22
LARRAÍN XIMENA|15
LARRONDO ENRIQUE Y ELSA HOLMGREN|16
LARRONDO IGNACIA|40
LARRONDO ISIDORA|40
LARRONDO JUAN ANDRÉS Y MARÍA PAZ DEL SOLAR|40
LARSON EUGENIO Y MARÍAPAZCANSECO|27
LAZARTE CHRISTIAN Y PAREJA|7
LEFREBRE CRISTIAN Y SEÑORA|8
LEON RODRIGO Y CARMEN GIACOMAN|16
LETELIER MAX Y PAREJA|32
LIRA SEBASTIÁN EI SIDORA FERNÁNDEZ|14
LOPEZ CLAUDIA|28
LOPEZ JUAN Y MYRIAM|39
LOPEZ MARÍA JOSÉ Y FELIPE VIVALDI|1
LOPEZ MARIANELA|28
LOPEZ PATRICIA|28
LOPEZ REINALDO Y SEÑORA|28
LUEGE GASPAR Y PAREJA|29
LUHRS AUGUSTO Y PAREJA|47
LUHRS B. FELIX Y SEÑORA|43
LUHRS C. FELIX Y SEÑORA|29
LUHRS CLEMENTE Y PAREJA|43
LUHRS JUAN IGNACIO Y ANITA|NOVIOS
LUHRS MARIA Y PAREJA|47
LUHRS NICOLAS Y PAREJA|NOVIOS
LUHRS R. FELIX Y SEÑORA|33
LUHRS R. PABLO Y SEÑORA|30
LUHRS S. PABLO|47
LUHRS SANTIAGO Y PAREJA|43
LUHRS SARA|47
LUHRS VICENTE|NOVIOS
HOLMGREN FLORENCIA|NOVIOS
LUHRS JUAN IGNACIO|NOVIOS
LUPINACCI PABLO|23
MARDONES ANDRES Y MARÍA JOSE PÉREZ|15
MARQUEZ DE LA PLATA ALFONSO Y SEÑORA|32
MARTINO GONZALO Y SEÑORA|32
MATHIEU ANDRES Y STEFANÍA ROSSOLINI|25
MCKLEIN ANDRES Y ALEJANDRA BALLIVIAN|37
MEDINA RAQUEL|39
MELLADO CLAUDIO Y LUNA SOTOMAYOR|36
MELLADO JUAN GABRIEL Y XIMENA CABRERA|36
MIQUEL LUCAS Y PAREJA|10
MOLLER MATIAS Y SEÑORA|9
MONTAN ANDRES Y CARMEN CID|36
MONTAN JUAN PABLO Y MACARENA MORENO|36
MONTANARI ANDRES Y SEÑORA|22
MUNIZAGA C. ESCIPION Y PAREJA|46
MUNIZAGA SARA Y PAREJA|18
MUÑIZ FRANCISCA Y MAURICIO IBAÑEZ|1
MUÑOZ MARCO Y SEÑORA|32
MUÑOZ MARÍA JESUS Y FRANCISCO CERDA|7
MUSALEM OSCAR Y SEÑORA|44
OESTREICHER CLAUDIO Y SEÑORA|30
OÑATE LUIS Y SEÑORA|39
ORELLANA JUAN PABLO Y SEÑORA|34
ORSINI REMO Y PAREJA|9
OVALLE CATALINA Y SEBSTIÁN|3
OYANEDEL ANDRES Y PAREJA|6
PALACIOS ANDRÉS Y JESU LARRONDO|40
PALACIOS ALEJANDRO Y ALEJANDRA KREBS|38
PAYO SCOCHTING Y JAVIERA BONGARDT|40
PEREZ DE ARCE RODRIGO|31
PÉREZ JORGE ANDRES Y MACARENA URZUA|15
PEREZ OSVALDO Y SEÑORA|44
PITTO ANA MARIA|23
PITTO VALERIA Y MARIDO|23
RABAT PELAYO Y SEÑORA|17
RAGGIO ANDRES Y SEÑORA|42
RAGGIO C. GONZALO Y PAREJA|6
RAGGIO CARLOS Y SEÑORA|42
RAGGIO CRISTOBAL Y SEÑORA|43
RAGGIO FELIPE Y SEÑORA|30
RAGGIO GONZALO Y SEÑORA|42
RAGGIO IGNACIO Y PAREJA|42
RAGGIO MAGDALENA Y PAREJA|6
RAGGIO MARIA EUGENIA Y PAREJA|6
RAMIREZ BENJAMIN Y PAREJA|11
RAMIREZ NICOLAS Y PAREJA|45
RASSMUSEN FRANCISCA Y MAX ROCHETTE|12
RECHARDT ISIDORA Y FELIPE RAMIREZ|1
REYES FRANCISCA Y MARIDO|35
RIESCO ALFREDO Y SEÑORA|45
RIESCO CRISTOBAL Y SEÑORA|46
RIOS DIEGO Y PAREJA|11
RODRIGUEZ B GABRIEL|29
RODRIGUEZ GABRIEL HIJO Y SEÑORA|47
RODRÍGUEZ JUAN CARLOS Y MÓNICA AYUSO|37
RODRÍGUEZ LUIS HERNAN Y CECILIA GARCÉS|21
RODRIGUEZ MARENGO MARIA Y AGUSTIN LAZARTE|2
RODRÍGUEZ FELIPE Y GABRIELA KREBS|38
ROJAS IGNACIA Y JOSE LUIS ROMERO|2
ROSEELOT JOSEFINA Y CARLOS DE MARTINI|13
ROSSELOT COLOMBA Y ACOMPAÑANTE|12
RUIZ TAGLE SEBASTIAN Y SEÑORA|22
SALINAS FRANCISCO Y SEÑORA|6
SANGRONIZ ITZIAR Y JUAN PIRIZ|4
SIERRA JOSE MANUEL Y CAROLA KUNCKELL|16
SILVA BALTAZAR|26
SILVA LOURDES|26
SILVA RAIMUNDO Y DANIELA HOLMGREN|NOVIOS
SOLARI CARLO|33
SOLARI PIERO Y SEÑORA|34
SOLARI SANDRO Y SEÑORA|34
SPIKING ALEJANDRA Y PAREJA|35
SUBERCASEAUX MARÍA JOSÉ Y JOSÉ MIGUEL RICALDE|1
TAGLE JORGE Y SEÑORA|34
TEJOS CONSUELO Y FRANCISCO BILBAO|7
URIARTE JOSEFINA Y CRESENTE RIESCO|13
URIARTE MARTIN Y ALEJANDRA GARCÍA|24
URZUA HERIBERTO Y SEÑORA|22
VALENZUELA CLEMENTE Y PAREJA|11
VALENZUELA GREGORY Y PAREJA|7
VENEGAS JAVIER Y SOFIA KREBS|38
VESZPREMY ANDRES Y JOSEFINA OPAZO|24
VIAL LEON Y PAREJA|10
VIAL MARISOL|29
VIDAURRE LUCÍA Y RODRIGO EDWARDS|3
VIER EDUARDO Y CATALINA ECHAVARRI|25
VILLELA BENJAMIN Y PAREJA|5
VILLELA CRISTINA|4
VILLELA VICENTE Y PAREJA|5
VINET ROBERT Y PAULA BRAND|27
VIVANCO JAVIERA Y MARIDO|5
ZUÑIGA PABLO Y SEÑORA|30
`;

const guests = rawGuests
  .trim()
  .split("\n")
  .map((line) => {
    const [name, table] = line.split("|");
    return {
      name: name.trim(),
      table: /^\d+$/.test(table) ? Number(table) : table.trim(),
      search: normalizeText(name),
    };
  });

const guestsByTable = guests.reduce((tables, guest) => {
  if (!tables.has(guest.table)) tables.set(guest.table, []);
  tables.get(guest.table).push(guest);
  return tables;
}, new Map());

const input = document.querySelector("#surname");
const result = document.querySelector("#result");
const clearButton = document.querySelector("#clearButton");

function normalizeText(value) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/Ñ/g, "N")
    .replace(/ñ/g, "n")
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, " ")
    .trim();
}

function titleName(value) {
  return value
    .toLocaleLowerCase("es-CL")
    .replace(/\p{L}+/gu, (word) => word[0].toLocaleUpperCase("es-CL") + word.slice(1));
}

function findMatches(query) {
  const normalized = normalizeText(query);
  if (normalized.length < 2) return [];

  const terms = normalized.split(/\s+/).filter(Boolean);
  return guests.filter((guest) =>
    terms.every((term) =>
      guest.search.split(" ").some((token) => token.startsWith(term)) ||
      guest.search.includes(term)
    )
  );
}

function renderEmpty(message = "Ingresa tu apellido para encontrar tu mesa.") {
  result.className = "result-panel empty";
  result.innerHTML = `<p>${message}</p>`;
}

function renderNotFound(query) {
  result.className = "result-panel not-found";
  result.innerHTML = `<p>No encontré “${escapeHtml(query)}”. Revisa si está escrito igual que en la invitación.</p>`;
}

function renderTable(table) {
  const tableGuests = guestsByTable.get(table) || [];
  result.className = "result-panel";
  result.innerHTML = `
    <h2 class="mesa-title">Mesa: ${escapeHtml(table)}</h2>
    <ul class="guest-list">
      ${tableGuests.map((guest) => `<li>${escapeHtml(titleName(guest.name))}</li>`).join("")}
    </ul>
  `;
}

function renderMatches(matches) {
  result.className = "result-panel";
  result.innerHTML = `
    <p class="matches-title">Encontré varias coincidencias. Elige tu nombre:</p>
    <ul class="match-list">
      ${matches
        .map(
          (guest, index) => `
            <li>
              <button class="match-button" type="button" data-index="${index}">
                <span class="match-name">${escapeHtml(titleName(guest.name))}</span>
                <span class="match-table">Mesa ${escapeHtml(guest.table)}</span>
              </button>
            </li>
          `
        )
        .join("")}
    </ul>
  `;

  result.querySelectorAll(".match-button").forEach((button) => {
    button.addEventListener("click", () => renderTable(matches[Number(button.dataset.index)].table));
  });
}

function updateSearch() {
  const query = input.value.trim();
  if (!query) {
    renderEmpty();
    return;
  }

  const matches = findMatches(query);
  if (!matches.length) {
    renderNotFound(query);
    return;
  }

  const tableNumbers = [...new Set(matches.map((guest) => guest.table))];
  if (matches.length === 1 || tableNumbers.length === 1) {
    renderTable(matches[0].table);
    return;
  }

  renderMatches(matches);
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

input.addEventListener("input", updateSearch);
clearButton.addEventListener("click", () => {
  input.value = "";
  input.focus();
  renderEmpty();
});

renderEmpty();
